spring.application.name=social-job-platform

# Cấu hình Database linh hoạt (Bảo mật 100%)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/db_tuyen_dung}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root_password}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Quản lý cấu trúc Database (Tuyệt đối không dùng create-drop)
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# Chỉ in log SQL khi code ở máy local
spring.jpa.show-sql=${SHOW_SQL:true}

firebase.service-account.path=classpath:firebase-service-account.json

# Azure Blob Storage
azure.storage.enabled=${AZURE_STORAGE_ENABLED:true}

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING:}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME:social-job-files}
azure.storage.public-base-url=${AZURE_STORAGE_PUBLIC_BASE_URL:https://socialjobstorage.blob.core.windows.net/social-job-files}

job.embedding.base-url=${JOB_EMBEDDING_BASE_URL:http://localhost:8000}
job.embedding.embed-path=${JOB_EMBEDDING_EMBED_PATH:/api/v1/jobs/embed}
job.embedding.timeout-millis=${JOB_EMBEDDING_TIMEOUT_MILLIS:10000}

bert.service.base-url=${BERT_SERVICE_BASE_URL:http://localhost:8000}
bert.service.score-path=${BERT_SERVICE_SCORE_PATH:/api/v1/score-cv}
bert.service.timeout-millis=${BERT_SERVICE_TIMEOUT_MILLIS:30000}
